# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Test image generation

on:
  push:
    paths:
      - 'src/**'
      - 'test/**'

permissions:
  contents: read

jobs:
  build_images:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/component-build-images.yml
    with:
      push: ${{ github.ref == 'refs/heads/main' }}
      version: latest
      ghcr_repo: ghcr.io/nudgebee/opentelemetry-demo
